### ISSUE TITLE
ERROR: routes.rb: undefined class AdminUser

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#101] opened 2020-02-03 12:25 UTC
On a brand new appdev_template generated app, `bin/setup` fails on gitpod with:

ERROR: routes.rb
undefined class AdminUser
/workspace/omnicalc-gui/config/routes.rb:2

rails aborted!
NameError: uninitialized constant AdminUser
/workspace/omnicalc-gui/db/seeds.rb:9:in `<main>'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/engine.rb:556:in `block in load_seed'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/engine.rb:676:in `with_inline_jobs'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/engine.rb:556:in `load_seed'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <main>'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/command.rb:48:in `invoke'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/workspace/omnicalc-gui/bin/rails:9:in `<top (required)>'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/home/gitpod/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/workspace/omnicalc-gui/bin/spring:15:in `require'
/workspace/omnicalc-gui/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

== Command ["rails db:seed"] failed ==

**Comment by jelaniwoods** [comment] 2020-02-03 23:16
I haven't been able to reproduce this yet, maybe it's somehow related to #100?

**Comment by jelaniwoods** [comment] 2020-05-06 19:31
Closing because I'm not able to reproduce.

**Closed by jelaniwoods** 2020-05-06 19:31 UTC
Labels: next up
